<?php
ini_set("display_errors",1);error_reporting(-1);
include_once("core/EquationInterface.php");
include_once("core/LogInterface.php");
include_once("core/LogAbstract.php");
include_once("Korusha/KorushaException.php");
include_once("Korusha/Linear.php");
include_once("Korusha/Log.php");
include_once("Korusha/Square.php");
?>
